# -*- conf -*-
# font=monaspicexenerdfont:size=10,ibmplexsansjp:size=10,notocoloremoji:size=10
font=ipamincho:size=14,notocoloremoji:size=10
font-size-adjustment=1px
resize-by-cells=no
resize-keep-grid=no
locked-title=yes
[scrollback]
lines=3000
[cursor]
blink=no
style=block
# [colors-dark]
[colors]
alpha=0.92
